# Generated by Django 3.2.20 on 2023-10-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_points',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, '-'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (16, '16'), (24, '24')], help_text='The amount of points this story takes up in the sprint', null=True, verbose_name='Story Points'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('5', '5'), ('8', '8'), ('13', '13'), ('21', '21'), ('34', '34'), ('Too large (89)', 'Too large (89)'), ('No idea (?)', 'No idea (?)'), ('1', '1'), ('2', '2'), ('4', '4'), ('8', '8'), ('16', '16'), ('24', '24')], max_length=200, verbose_name='Choice'),
        ),
    ]
